### PR TITLE
[RTR] Small fix + vtp cleaner

### PR DESCRIPTION
**Pull request by Ipuch**
Perfect 
- I had a problem with no range in the osim file. -> Solved
- I had a problem with .vtp files that were not well displayed in bioviz because they were not triangles. -> Solved

This change is [Reviewable](https://reviewable.io/reviews/pyomeca/osim_to_biomod/5)
- - -

### CODE REVIEW

**Comment by Ipuch** [comment]
@pariterre and @aceglia can you validate that ? :)

**Comment by pariterre** [comment]
I let @aceglia confirming and merging

**Review by aceglia — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/osim_to_biomod/5)* status: all files reviewed, 5 unresolved discussions (waiting on @Ipuch)

___
*[`example/example.py` line 16 at r2](https://reviewable.io/reviews/pyomeca/osim_to_biomod/5#-Nhh5cX94vIIRcsSfQjE:-Nhh5cX94vIIRcsSfQjF:bq2jm5o) ([raw file](https://github.com/pyomeca/osim_to_biomod/blob/080cc9d72deb2e330482f95c3ed291063c850e21/example/example.py#L16)):*
> ```Python
>         print_warnings=True,
>         print_general_informations=True,
>         vtp_to_triangles=True,
> ```

vtp_polygon_to_triangle ? 
___
*[`osim_to_biomod/converter.py` line 740 at r2](https://reviewable.io/reviews/pyomeca/osim_to_biomod/5#-Nhh5snj4anZvmaFuLLf:-Nhh5snj4anZvmaFuLLg:bg1fbuf) ([raw file](https://github.com/pyomeca/osim_to_biomod/blob/080cc9d72deb2e330482f95c3ed291063c850e21/osim_to_biomod/converter.py#L740)):*
> ```Python
>         self.mesh_dir = "Geometry" if mesh_dir is None else mesh_dir
> 
>         self.new_mesh_dir = self.mesh_dir + "_cleaned"
> ```

The term clean seems a bit inappropriate. Simplified, processed ... ? 
___
*[`osim_to_biomod/mesh_cleaner.py` line 149 at r2](https://reviewable.io/reviews/pyomeca/osim_to_biomod/5#-Nhh5G4FBzaPDdyKj4mA:-Nhh5G4FBzaPDdyKj4mB:b-i8xh7g) ([raw file](https://github.com/pyomeca/osim_to_biomod/blob/080cc9d72deb2e330482f95c3ed291063c850e21/osim_to_biomod/mesh_cleaner.py#L149)):*
> ```Python
>         # get only the non-nan values
>         current_polygon = polygons[poly_idx, np.isnan(polygons[poly_idx]) == False]
>         # current_normal = normals[poly_idx]
> ```

Usefull ? if not remove the  comment.
___
*[`osim_to_biomod/mesh_cleaner.py` line 157 at r2](https://reviewable.io/reviews/pyomeca/osim_to_biomod/5#-Nhh5KaC83qId-lXJXp5:-Nhh5KaC83qId-lXJXp6:b-86mnwo) ([raw file](https://github.com/pyomeca/osim_to_biomod/blob/080cc9d72deb2e330482f95c3ed291063c850e21/osim_to_biomod/mesh_cleaner.py#L157)):*
> ```Python
>             triangles.append(np.column_stack([polygons[poly_idx, 0], polygons[poly_idx, i], polygons[poly_idx, i + 1]]))
> 
>         # # Duplicate normals
> ```

Idem 
___
*[`osim_to_biomod/mesh_cleaner.py` line 171 at r2](https://reviewable.io/reviews/pyomeca/osim_to_biomod/5#-Nhh5NoDBJ8xj-Wrd4zy:-Nhh5NoDBJ8xj-Wrd4zz:bn2mp7h) ([raw file](https://github.com/pyomeca/osim_to_biomod/blob/080cc9d72deb2e330482f95c3ed291063c850e21/osim_to_biomod/mesh_cleaner.py#L171)):*
> ```Python
>         np.vstack([polygons[polygons_with_3_edges, :3], *triangles]),
>         nodes,
>         # np.vstack([normals[polygons_with_3_edges, :3], *new_normals]),
> ```

To remove ?

**Review by Ipuch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/osim_to_biomod/5)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @aceglia)

___
*[`example/example.py` line 16 at r2](https://reviewable.io/reviews/pyomeca/osim_to_biomod/5#-Nhh5cX94vIIRcsSfQjE:-Nhha0Pj-NR5fFl48BFc:bb7f2mf) ([raw file](https://github.com/pyomeca/osim_to_biomod/blob/080cc9d72deb2e330482f95c3ed291063c850e21/example/example.py#L16)):*
<details><summary><i>Previously, aceglia wrote…</i></summary><blockquote>

vtp_polygon_to_triangle ?
</blockquote></details>

done
___
*[`osim_to_biomod/converter.py` line 740 at r2](https://reviewable.io/reviews/pyomeca/osim_to_biomod/5#-Nhh5snj4anZvmaFuLLf:-Nhh_ZlL4C7ZBaevmUDv:b-896fix) ([raw file](https://github.com/pyomeca/osim_to_biomod/blob/080cc9d72deb2e330482f95c3ed291063c850e21/osim_to_biomod/converter.py#L740)):*
<details><summary><i>Previously, aceglia wrote…</i></summary><blockquote>

The term clean seems a bit inappropriate. Simplified, processed ... ?
</blockquote></details>

Done.
___
*[`osim_to_biomod/mesh_cleaner.py` line 149 at r2](https://reviewable.io/reviews/pyomeca/osim_to_biomod/5#-Nhh5G4FBzaPDdyKj4mA:-Nhh_kEVCMeFHLyrHl1j:bb6un1j) ([raw file](https://github.com/pyomeca/osim_to_biomod/blob/080cc9d72deb2e330482f95c3ed291063c850e21/osim_to_biomod/mesh_cleaner.py#L149)):*
<details><summary><i>Previously, aceglia wrote…</i></summary><blockquote>

Usefull ? if not remove the  comment.
</blockquote></details>

Done
___
*[`osim_to_biomod/mesh_cleaner.py` line 157 at r2](https://reviewable.io/reviews/pyomeca/osim_to_biomod/5#-Nhh5KaC83qId-lXJXp5:-Nhh_sfJ469_rbtwO19f:bb6un1j) ([raw file](https://github.com/pyomeca/osim_to_biomod/blob/080cc9d72deb2e330482f95c3ed291063c850e21/osim_to_biomod/mesh_cleaner.py#L157)):*
<details><summary><i>Previously, aceglia wrote…</i></summary><blockquote>

Idem
</blockquote></details>

Done
___
*[`osim_to_biomod/mesh_cleaner.py` line 171 at r2](https://reviewable.io/reviews/pyomeca/osim_to_biomod/5#-Nhh5NoDBJ8xj-Wrd4zy:-Nhh_tLW1CX5hrIPjqv1:bb6un1j) ([raw file](https://github.com/pyomeca/osim_to_biomod/blob/080cc9d72deb2e330482f95c3ed291063c850e21/osim_to_biomod/mesh_cleaner.py#L171)):*
<details><summary><i>Previously, aceglia wrote…</i></summary><blockquote>

To remove ?
</blockquote></details>

Done

**Pull request merged**
